# **WEEK-03**

**Q.1: Write a Python program to read a number and check whether it is even or odd.**

In [ ]:
# Problem 1:
num = int(input("Enter any number: "))
if (num%2 == 0):
  print("Even number!!!: ",num)
else:
  print("Odd number!!!: ",num)

Enter any number: 0
Even number!!!:  0


**Q.2: Write a Python program to find the largest of three numbers using conditional statements.**

In [ ]:
# Problem 2:
n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))
n3 = int(input("Enter third number: "))

if (n1 > n2) and (n2 > n3):
  print("First is the greatest: ", n1)

elif(n2 > n1) and (n2 > n3):
  print("Second is the greatest: ", n2)

elif  (n1 == n2) and (n2 == n3):
  print("All are equal!!")

else:
    print("Third is the greatest: ", n3)

Enter first number: -8
Enter second number: 7
Enter third number: 2
Second is the greatest:  7


**Q.3: Write a Python program to generate the first n Fibonacci numbers using a loop.**

In [ ]:
#Problem 3:
term= int(input("Enter number of terms: "))
a = 0
b = 1
for i in range(term):
  print(a)
  c = a + b
  a = b
  b = c

Enter number of terms: 6
0
1
1
2
3
5


**Q.4: Write a Python program to count the number of vowels in a given string.**

In [ ]:
# Problem 4:
string = input("Enter any string: ")
count = 0
vowel = set("aeiouAEIOU")
for c in string:
  if c in vowel:
    count += 1
print("Number of vowels: ", count)

Enter any string: Noon
Number of vowels:  2


# **WEEK-04**

**Q.1: Create a list of numbers and find the sum and average of the list.**

In [ ]:
# Problem 1

n = int(input("Enter how many numbers: "))

numbers = []

for i in range(n):
    num = float(input(f"Enter number {i+1}: "))
    numbers.append(num)

total = sum(numbers)
avg = total/n

print("List of numbers:", numbers)
print("Sum:", total)
print("Average is: ", avg)

Enter how many numbers: 4
Enter number 1: 3
Enter number 2: 4
Enter number 3: 2
Enter number 4: 6
List of numbers: [3.0, 4.0, 2.0, 6.0]
Sum: 15.0
Average is:  3.75


**Q2: Write a function to check whether a given string is a palindrome.**

In [ ]:
# Problem 2
text = input("Enter a string: ")

reverse = ""
for char in text:
    reverse = char + reverse

if text == reverse:
    print("Palindrome")
else:
    print("Not a Palindrome")

Enter a string: 121
Palindrome


**Q3: Create a dictionary of student names and marks. Display students scoring above 75.**

In [ ]:
# Problem 3

students = {
    "Motiur Rahman": 82,
    "Tameem": 67,
    "Arbab": 91,
    "Fuad": 74,
    "Ali": 88,
    "Ayaan": 74
}

print("Students scoring above 75:")

for name, marks in students.items():
    if marks > 75:
        print(name, ":", marks)

Students scoring above 75:
Motiur Rahman : 82
Arbab : 91
Ali : 88


**Q4: Write a program to sort a list in ascending and descending order.**

In [ ]:
# Problem 4
numbers = [45, 12, 89, 23, 7,67,43,13]

asc = numbers.copy()
n = len(asc)

for i in range(n):
    for j in range(0, n - i - 1):
        if asc[j] > asc[j + 1]:
            temp = asc[j]
            asc[j] = asc[j + 1]
            asc[j + 1] = temp

print("Ascending order:", asc)

desc = numbers.copy()

for i in range(n):
    for j in range(0, n - i - 1):
        if desc[j] < desc[j + 1]:
            temp = desc[j]
            desc[j] = desc[j + 1]
            desc[j + 1] = temp

print("Descending order:", desc)

Ascending order: [7, 12, 13, 23, 43, 45, 67, 89]
Descending order: [89, 67, 45, 43, 23, 13, 12, 7]


# **WEEK-05**

**Q1: Create a NumPy array and display its shape, size, and data type.**

In [ ]:

#Problem 1
import numpy as np
ar = np.array([3,8,5,9,2,83])

shp = ar.shape

sz = ar.size

dt = ar.dtype

print("Array: ",ar)
print("Shape: ",shp)
print("Size: ", sz)
print("Data type: ",dt)

Array:  [ 3  8  5  9  2 83]
Shape:  (6,)
Size:  6
Data type:  int64


**Q2: Perform at least five basic arithmetic operations on NumPy arrays (addition of two arrays, subtraction, etc.).**

In [ ]:
# Problem 2
import numpy as np
array = np.array([2,6,7,12,15])
array2 = np.array([2,7,3,8,9])
sum = array + array2
sub = array - array2
prod = array * array2
div = array / array2
mod = array % array2

print(sum)
print(sub)
print(prod)
print(div)
print(mod)

[ 4 13 10 20 24]
[ 0 -1  4  4  6]
[  4  42  21  96 135]
[1.         0.85714286 2.33333333 1.5        1.66666667]
[0 6 1 4 6]


**Q3: Create a NumPy array from having numbers between 1 to 100 and print only the prime numbers in them.**

In [ ]:
# Problem 3
import numpy as np
nums = np.random.randint(1, 101, 30)

print("Random Numbers :",nums)

print("\nPrime Numbers: ")

for n in nums:
    if n > 1:
        for i in range(2, n):
            if n % i == 0:
                break
        else:
            print(n, end=" ")

Random Numbers : [71 28 77 60 87 12  9 97 21  2 66 58 44 28 43 72 45 92 16 73 26 83 33 49
 86  1 31 15 76 85]

Prime Numbers: 
71 97 2 43 73 83 31 

**Q4: Take a NumPy array and demonstrate indexing and slicing on it.**

In [ ]:
# Problem 4
import numpy as np
ar = np.array([3,2,8,9,12,34,32,56])
print("Print on indexing: " ,ar[2])
print("Slicing : ",ar[2:6])
print("Slicing :",ar[-2:7])

Print on indexing:  8
Slicing :  [ 8  9 12 34]
Slicing : [32]


**WEEK_6**

In [ ]:
# Problem 1
import numpy as np
array = np.random.randint(1,10,(5))
print("Original array: ",array)
print("The mean is : ",np.mean(array))
print("The median is : ",np.median(array))
print("The standard deviation is : ",np.std(array))



Original array:  [7 5 7 8 3]
The mean is :  6.0
The median is :  7.0
The standard deviation is :  1.7888543819998317


In [ ]:
# Problem 2
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))
print("First array: \n",arr1)
print("Second array: \n",arr2)
add = arr1 + arr2
print("The sum of both arrays is:\n",add)

prod = arr1 * arr2
print("The simple element by element multiplication is:\n",prod)

print("\nMatrix multiplication: \n")
a = np.random.randint(1,10,(2,3))
b = np.random.randint(1,10,(3,2))
print("First matrix is:",a)
print("Second matrix is:", b)
print("Matrix multiplication is :\n",np.matmul(a,b))


First array: 
 [[6 2 4]
 [8 1 7]]
Second array: 
 [[3 2 7]
 [5 1 2]]
The sum of both arrays is:
 [[ 9  4 11]
 [13  2  9]]
The simple element by element multiplication is:
 [[18  4 28]
 [40  1 14]]

Matrix multiplication: 

First matrix is: [[7 5 7]
 [3 8 8]]
Second matrix is: [[8 3]
 [3 1]
 [1 1]]
Matrix multiplication is :
 [[78 33]
 [56 25]]


In [ ]:
# Problem 3
import numpy as np
ar1 = np.random.randint(1,100,10)
print(ar1)
print("The max element of array is: ",np.max(ar1))
print("The minimum element of an array is: ",np.min(ar1))

[61 39 10 91 43  8 52 33 16 64]
The max element of array is:  91
The minimum element of an array is:  8


In [ ]:
# Problem 4
import numpy as np
p = np.random.randint(1,50,(10))
print("The original array is:\n",p)
print("The new matrix is:\n",np.reshape(p,(2,5)))
print("The matrix is:\n" ,np.reshape(p,(5,2)))

The original array is:
 [12 16 41 14 21 41 38 20  2 20]
The new matrix is:
 [[12 16 41 14 21]
 [41 38 20  2 20]]
The matrix is:
 [[12 16]
 [41 14]
 [21 41]
 [38 20]
 [ 2 20]]
